# Generated by Django 2.1.2 on 2018-10-25 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0009_remove_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='password',
            field=models.CharField(default='admin', max_length=254),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='username',
            field=models.CharField(default='admin', max_length=254),
        ),
    ]
