# Generated by Django 2.1.2 on 2018-10-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_auto_20181028_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_picture/'),
        ),
    ]
