# Generated by Django 2.1.2 on 2019-01-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_auto_20181031_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='full_name',
            field=models.CharField(default='dane jone', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_detail',
            name='profile_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_link',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/avatar.jpeg', upload_to='profile_picture/'),
        ),
    ]
